#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if ! which ansible &> /dev/null; then
  echo -ne "Cannot find ansible, Installing..."
  sudo yum -y -q install ansible
  echo "Done."
fi

ansible-playbook -K playbook.yml
