set background=dark
colorscheme jellybeans

au WinLeave * set nocursorline nocursorcolumn
au WinEnter * set cursorline cursorcolumn

set cursorline
set cursorcolumn

set guifont=Fantasque\ Sans\ Mono\ 10
set encoding=utf-8
