#!/bin/bash

[[ -f $HOME/.Xdefaults ]] && xrdb -merge $HOME/.Xdefaults
[[ -f $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources

cat $HOME/.i3/conf.d/*.conf > $HOME/.i3/config

# The bid'ness
exec i3
