#!/bin/bash

[[ -f $HOME/.Xdefaults ]] && xrdb -merge $HOME/.Xdefaults
[[ -f $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources

$HOME/bin/set-random-background
$HOME/bin/rebuild-font-cache

cat $HOME/.i3/conf.d/*.conf > $HOME/.i3/config

# The bid'ness
exec i3
