#!/bin/bash

set -o errexit
set -o pipefail

notify() {
  notify-send -u normal -a "Brightness: " "$@"
}

get_brightness() {
  echo -n "$(xbacklight -get | cut -d "." -f1)%"
}

case "$@" in
  "up")
    xbacklight -inc 10%
    notify "$(get_brightness)";;
  "down")
    xbacklight -dec 10%
    notify "$(get_brightness)";;
  "reset")
    xbacklight -set 100%
    notify "$(get_brightness)";;
esac
