#!/bin/bash

set -o errexit
set -o pipefail

get_volume() {
  pactl list sinks | grep Volume: | head -1 | awk '{print $5}'
}

muted() {
  pactl list sinks | grep Mute: | awk '{print $2}' 
}

toggle_mute() {
  pactl set-sink-mute @DEFAULT_SINK@ toggle
}

set_volume() {
  pactl set-sink-volume @DEFAULT_SINK@ -- ${@}%
}

reset_volume() {
  pactl set-sink-volume @DEFAULT_SINK@ -- 75%
}

notify() {
  notify-send -u normal -a "Volume: " "$@"
}

case "$@" in
  "reset")
    set_volume 75
    notify "Volume Restores ($(get_volume))";;
  "down")
    set_volume -5
    notify "$(get_volume)";;
  "up")
    set_volume +5
    notify "$(get_volume)";;
  "mute")
    toggle_mute
    ([[ "$(muted)" == "yes" ]] && notify "Muted") || notify "Unmuted ($(get_volume))";;
  "halfmute")
    [[ "$(get_volume)" != "30%" ]] && set_volume 30 && notify "Mute ($(get_volume))";;
esac
